import React from "react";

const Hand = ({ flags, setFlags }) => {
  return (
    <div className="tableDiv">
      <table border="1">
        <tr>
          <td>
            <button
              onClick={() => {
                setFlags({
                  ...flags,
                  flag1: 2,
                });
              }}
            >
              101
            </button>
          </td>

          <td>
            <button>102</button>
          </td>
          <td>
            <button>103</button>
          </td>
          <td>
            <button>104</button>
          </td>
          <td>
            <button>105</button>
          </td>
          <td>
            <button>106</button>
          </td>
        </tr>
        <tr>
          <td>
            <button
              onClick={() => {
                setFlags({
                  ...flags,
                  flag2: 2,
                });
              }}
            >
              201
            </button>
          </td>
          <td>
            <button>202</button>
          </td>
          <td>
            <button>203</button>
          </td>
          <td>
            <button>204</button>
          </td>
          <td>
            <button>205</button>
          </td>
          <td>
            <button>206</button>
          </td>
        </tr>
        <tr>
          <td>
            <button
              onClick={() => {
                setFlags({
                  ...flags,
                  flag3: 2,
                });
              }}
            >
              301
            </button>
          </td>
          <td>
            <button>302</button>
          </td>
          <td>
            <button>303</button>
          </td>
          <td>
            <button>304</button>
          </td>
          <td>
            <button>305</button>
          </td>
          <td>
            <button>306</button>
          </td>
        </tr>
        <tr>
          <td>
            <button
              onClick={() => {
                setFlags({
                  ...flags,
                  flag4: 2,
                });
              }}
            >
              401
            </button>
          </td>
          <td>
            <button>402</button>
          </td>
          <td>
            <button>403</button>
          </td>
          <td>
            <button>404</button>
          </td>
          <td>
            <button>405</button>
          </td>
          <td>
            <button>406</button>
          </td>
        </tr>
        <tr>
          <td>
            <button>501</button>
          </td>
          <td>
            <button>502</button>
          </td>
          <td>
            <button>503</button>
          </td>
          <td>
            <button>504</button>
          </td>
          <td>
            <button>505</button>
          </td>
          <td>
            <button>506</button>
          </td>
        </tr>
        <tr>
          <td>
            <button>601</button>
          </td>
          <td>
            <button>602</button>
          </td>
          <td>
            <button>603</button>
          </td>
          <td>
            <button>604</button>
          </td>
          <td>
            <button>605</button>
          </td>
          <td>
            <button>606</button>
          </td>
        </tr>
        <tr>
          <td>
            <button>701</button>
          </td>
          <td>
            <button>702</button>
          </td>
          <td>
            <button>703</button>
          </td>
          <td>
            <button>704</button>
          </td>
          <td>
            <button>705</button>
          </td>
          <td>
            <button>706</button>
          </td>
        </tr>
        <tr>
          <td>
            <button>801</button>
          </td>
          <td>
            <button>802</button>
          </td>
          <td>
            <button>803</button>
          </td>
          <td>
            <button>804</button>
          </td>
          <td>
            <button>805</button>
          </td>
          <td>
            <button>806</button>
          </td>
        </tr>
        <tr>
          <td>
            <button>901</button>
          </td>
          <td>
            <button>902</button>
          </td>
          <td>
            <button>903</button>
          </td>
          <td>
            <button>904</button>
          </td>
          <td>
            <button>905</button>
          </td>
          <td>
            <button>906</button>
          </td>
        </tr>
        <tr>
          <td>
            <button>1001</button>
          </td>
          <td>
            <button>1002</button>
          </td>
          <td>
            <button>1003</button>
          </td>
          <td>
            <button>1004</button>
          </td>
          <td>
            <button>1005</button>
          </td>
          <td>
            <button>1006</button>
          </td>
        </tr>
      </table>
    </div>
  );
};

export default Hand;
