import React from "react";

const Hand2 = ({ flags, setFlags }) => {
  const choiceColor = (type) => {
    if (type === 2) return "파랑";
    else if (type === 1) return "빨강";
    else return "흰색";
  };
  return (
    <div>
      <h1>핸드 그래프 들어갈곳</h1>
      <table border="1">
        <tr>
          <td>{choiceColor(flags["flag1"])}</td>
          <td>
            <>2</>
          </td>
          <td>
            <>3</>
          </td>
          <td>
            <>4</>
          </td>
          <td>
            <>5</>
          </td>
          <td>
            <>6</>
          </td>
        </tr>
        <tr>
          <td>{choiceColor(flags["flag2"])}</td>
          <td>
            <>2</>
          </td>
          <td>
            <>3</>
          </td>
          <td>
            <>4</>
          </td>
          <td>
            <>5</>
          </td>
          <td>
            <>6</>
          </td>
        </tr>
        <tr>
          <td>{choiceColor(flags["flag3"])}</td>
          <td>
            <>2</>
          </td>
          <td>
            <>3</>
          </td>
          <td>
            <>4</>
          </td>
          <td>
            <>5</>
          </td>
          <td>
            <>6</>
          </td>
        </tr>
        <tr>
          <td>{choiceColor(flags["flag4"])}</td>
          <td>
            <>2</>
          </td>
          <td>
            <>3</>
          </td>
          <td>
            <>4</>
          </td>
          <td>
            <>5</>
          </td>
          <td>
            <>6</>
          </td>
        </tr>
        <tr>
          <td>
            <>1</>
          </td>
          <td>
            <>2</>
          </td>
          <td>
            <>3</>
          </td>
          <td>
            <>4</>
          </td>
          <td>
            <>5</>
          </td>
          <td>
            <>6</>
          </td>
        </tr>
        <tr>
          <td>
            <>1</>
          </td>
          <td>
            <>2</>
          </td>
          <td>
            <>3</>
          </td>
          <td>
            <>4</>
          </td>
          <td>
            <>5</>
          </td>
          <td>
            <>6</>
          </td>
        </tr>
        <tr>
          <td>
            <>1</>
          </td>
          <td>
            <>2</>
          </td>
          <td>
            <>3</>
          </td>
          <td>
            <>4</>
          </td>
          <td>
            <>5</>
          </td>
          <td>
            <>6</>
          </td>
        </tr>
        <tr>
          <td>
            <>1</>
          </td>
          <td>
            <>2</>
          </td>
          <td>
            <>3</>
          </td>
          <td>
            <>4</>
          </td>
          <td>
            <>5</>
          </td>
          <td>
            <>6</>
          </td>
        </tr>
        <tr>
          <td>
            <>1</>
          </td>
          <td>
            <>2</>
          </td>
          <td>
            <>3</>
          </td>
          <td>
            <>4</>
          </td>
          <td>
            <>5</>
          </td>
          <td>
            <>6</>
          </td>
        </tr>
        <tr>
          <td>
            <>1</>
          </td>
          <td>
            <>2</>
          </td>
          <td>
            <>3</>
          </td>
          <td>
            <>4</>
          </td>
          <td>
            <>5</>
          </td>
          <td>
            <>6</>
          </td>
        </tr>
      </table>
    </div>
  );
};

export default Hand2;
