import React from "react";

const Hoist = ({ flags, setFlags }) => {
  return (
    <div>
      <h1>호이스트 그래프 들어갈곳</h1>
      <table border="1">
        <tr>
          <td>
            <button
              onClick={() => {
                setFlags({
                  ...flags,
                  flag1: 1,
                });
              }}
            >
              1
            </button>
          </td>

          <td>
            <button>2</button>
          </td>
          <td>
            <button>3</button>
          </td>
          <td>
            <button>4</button>
          </td>
          <td>
            <button>5</button>
          </td>
          <td>
            <button>6</button>
          </td>
        </tr>
        <tr>
          <td>
            <button
              onClick={() => {
                setFlags({
                  ...flags,
                  flag2: 1,
                });
              }}
            >
              1
            </button>
          </td>
          <td>
            <button>2</button>
          </td>
          <td>
            <button>3</button>
          </td>
          <td>
            <button>4</button>
          </td>
          <td>
            <button>5</button>
          </td>
          <td>
            <button>6</button>
          </td>
        </tr>
        <tr>
          <td>
            <button
              onClick={() => {
                setFlags({
                  ...flags,
                  flag3: 1,
                });
              }}
            >
              1
            </button>
          </td>
          <td>
            <button>2</button>
          </td>
          <td>
            <button>3</button>
          </td>
          <td>
            <button>4</button>
          </td>
          <td>
            <button>5</button>
          </td>
          <td>
            <button>6</button>
          </td>
        </tr>
        <tr>
          <td>
            <button
              onClick={() => {
                setFlags({
                  ...flags,
                  flag4: 1,
                });
              }}
            >
              1
            </button>
          </td>
          <td>
            <button>2</button>
          </td>
          <td>
            <button>3</button>
          </td>
          <td>
            <button>4</button>
          </td>
          <td>
            <button>5</button>
          </td>
          <td>
            <button>6</button>
          </td>
        </tr>
        <tr>
          <td>
            <button>1</button>
          </td>
          <td>
            <button>2</button>
          </td>
          <td>
            <button>3</button>
          </td>
          <td>
            <button>4</button>
          </td>
          <td>
            <button>5</button>
          </td>
          <td>
            <button>6</button>
          </td>
        </tr>
        <tr>
          <td>
            <button>1</button>
          </td>
          <td>
            <button>2</button>
          </td>
          <td>
            <button>3</button>
          </td>
          <td>
            <button>4</button>
          </td>
          <td>
            <button>5</button>
          </td>
          <td>
            <button>6</button>
          </td>
        </tr>
        <tr>
          <td>
            <button>1</button>
          </td>
          <td>
            <button>2</button>
          </td>
          <td>
            <button>3</button>
          </td>
          <td>
            <button>4</button>
          </td>
          <td>
            <button>5</button>
          </td>
          <td>
            <button>6</button>
          </td>
        </tr>
        <tr>
          <td>
            <button>1</button>
          </td>
          <td>
            <button>2</button>
          </td>
          <td>
            <button>3</button>
          </td>
          <td>
            <button>4</button>
          </td>
          <td>
            <button>5</button>
          </td>
          <td>
            <button>6</button>
          </td>
        </tr>
        <tr>
          <td>
            <button>1</button>
          </td>
          <td>
            <button>2</button>
          </td>
          <td>
            <button>3</button>
          </td>
          <td>
            <button>4</button>
          </td>
          <td>
            <button>5</button>
          </td>
          <td>
            <button>6</button>
          </td>
        </tr>
        <tr>
          <td>
            <button>1</button>
          </td>
          <td>
            <button>2</button>
          </td>
          <td>
            <button>3</button>
          </td>
          <td>
            <button>4</button>
          </td>
          <td>
            <button>5</button>
          </td>
          <td>
            <button>6</button>
          </td>
        </tr>
      </table>
    </div>
  );
};

export default Hoist;
