import React from "react";

const PL = () => {
  return (
    <div>
      <h1>pl 그래프 들어갈곳</h1>
      <table border="1">
        <tr>
          <td>
            <button>1</button>
          </td>

          <td>
            <button>2</button>
          </td>
          <td>
            <button>3</button>
          </td>
          <td>
            <button>4</button>
          </td>
          <td>
            <button>5</button>
          </td>
          <td>
            <button>6</button>
          </td>
        </tr>
        <tr>
          <td>
            <button>1</button>
          </td>
          <td>
            <button>2</button>
          </td>
          <td>
            <button>3</button>
          </td>
          <td>
            <button>4</button>
          </td>
          <td>
            <button>5</button>
          </td>
          <td>
            <button>6</button>
          </td>
        </tr>
        <tr>
          <td>
            <button>1</button>
          </td>
          <td>
            <button>2</button>
          </td>
          <td>
            <button>3</button>
          </td>
          <td>
            <button>4</button>
          </td>
          <td>
            <button>5</button>
          </td>
          <td>
            <button>6</button>
          </td>
        </tr>
        <tr>
          <td>
            <button>1</button>
          </td>
          <td>
            <button>2</button>
          </td>
          <td>
            <button>3</button>
          </td>
          <td>
            <button>4</button>
          </td>
          <td>
            <button>5</button>
          </td>
          <td>
            <button>6</button>
          </td>
        </tr>
        <tr>
          <td>
            <button>1</button>
          </td>
          <td>
            <button>2</button>
          </td>
          <td>
            <button>3</button>
          </td>
          <td>
            <button>4</button>
          </td>
          <td>
            <button>5</button>
          </td>
          <td>
            <button>6</button>
          </td>
        </tr>
        <tr>
          <td>
            <button>1</button>
          </td>
          <td>
            <button>2</button>
          </td>
          <td>
            <button>3</button>
          </td>
          <td>
            <button>4</button>
          </td>
          <td>
            <button>5</button>
          </td>
          <td>
            <button>6</button>
          </td>
        </tr>
        <tr>
          <td>
            <button>1</button>
          </td>
          <td>
            <button>2</button>
          </td>
          <td>
            <button>3</button>
          </td>
          <td>
            <button>4</button>
          </td>
          <td>
            <button>5</button>
          </td>
          <td>
            <button>6</button>
          </td>
        </tr>
        <tr>
          <td>
            <button>1</button>
          </td>
          <td>
            <button>2</button>
          </td>
          <td>
            <button>3</button>
          </td>
          <td>
            <button>4</button>
          </td>
          <td>
            <button>5</button>
          </td>
          <td>
            <button>6</button>
          </td>
        </tr>
        <tr>
          <td>
            <button>1</button>
          </td>
          <td>
            <button>2</button>
          </td>
          <td>
            <button>3</button>
          </td>
          <td>
            <button>4</button>
          </td>
          <td>
            <button>5</button>
          </td>
          <td>
            <button>6</button>
          </td>
        </tr>
        <tr>
          <td>
            <button>1</button>
          </td>
          <td>
            <button>2</button>
          </td>
          <td>
            <button>3</button>
          </td>
          <td>
            <button>4</button>
          </td>
          <td>
            <button>5</button>
          </td>
          <td>
            <button>6</button>
          </td>
        </tr>
      </table>
    </div>
  );
};

export default PL;
