import React from "react";

const PL2 = () => {
  return (
    <div>
      <h1>pl 그래프 들어갈곳</h1>
      <table border="1">
        <tr>
          <td>
            <>1</>
          </td>
          <td>
            <>2</>
          </td>
          <td>
            <>3</>
          </td>
          <td>
            <>4</>
          </td>
          <td>
            <>5</>
          </td>
          <td>
            <>6</>
          </td>
        </tr>
        <tr>
          <td>
            <>1</>
          </td>
          <td>
            <>2</>
          </td>
          <td>
            <>3</>
          </td>
          <td>
            <>4</>
          </td>
          <td>
            <>5</>
          </td>
          <td>
            <>6</>
          </td>
        </tr>
        <tr>
          <td>
            <>1</>
          </td>
          <td>
            <>2</>
          </td>
          <td>
            <>3</>
          </td>
          <td>
            <>4</>
          </td>
          <td>
            <>5</>
          </td>
          <td>
            <>6</>
          </td>
        </tr>
        <tr>
          <td>
            <>1</>
          </td>
          <td>
            <>2</>
          </td>
          <td>
            <>3</>
          </td>
          <td>
            <>4</>
          </td>
          <td>
            <>5</>
          </td>
          <td>
            <>6</>
          </td>
        </tr>
        <tr>
          <td>
            <>1</>
          </td>
          <td>
            <>2</>
          </td>
          <td>
            <>3</>
          </td>
          <td>
            <>4</>
          </td>
          <td>
            <>5</>
          </td>
          <td>
            <>6</>
          </td>
        </tr>
        <tr>
          <td>
            <>1</>
          </td>
          <td>
            <>2</>
          </td>
          <td>
            <>3</>
          </td>
          <td>
            <>4</>
          </td>
          <td>
            <>5</>
          </td>
          <td>
            <>6</>
          </td>
        </tr>
        <tr>
          <td>
            <>1</>
          </td>
          <td>
            <>2</>
          </td>
          <td>
            <>3</>
          </td>
          <td>
            <>4</>
          </td>
          <td>
            <>5</>
          </td>
          <td>
            <>6</>
          </td>
        </tr>
        <tr>
          <td>
            <>1</>
          </td>
          <td>
            <>2</>
          </td>
          <td>
            <>3</>
          </td>
          <td>
            <>4</>
          </td>
          <td>
            <>5</>
          </td>
          <td>
            <>6</>
          </td>
        </tr>
        <tr>
          <td>
            <>1</>
          </td>
          <td>
            <>2</>
          </td>
          <td>
            <>3</>
          </td>
          <td>
            <>4</>
          </td>
          <td>
            <>5</>
          </td>
          <td>
            <>6</>
          </td>
        </tr>
        <tr>
          <td>
            <>1</>
          </td>
          <td>
            <>2</>
          </td>
          <td>
            <>3</>
          </td>
          <td>
            <>4</>
          </td>
          <td>
            <>5</>
          </td>
          <td>
            <>6</>
          </td>
        </tr>
      </table>
    </div>
  );
};

export default PL2;
